### PR TITLE
Make hof-emailer support replyTo

### PR DESCRIPTION
**Pull request by easternbloc**
I'm pretty sure this isn't supported atm even though we think it's there...

### CODE REVIEW

**Comment by JoeChapman** [comment]
Why do you think it's not supported? And how does removing the option - there in case it is supported - will fix your email related problem?

**Comment by easternbloc** [comment]
I think it's not supported because when you put a replyTo into our config it doesn't work because as far as I can see we don't pass the option to nodemailer.

I don't remove the option I fall back to from if no replyTo is supplied to stop the code from breaking. This is explained in the tests....

**Comment by JoeChapman** [comment]
sorry, I see. so we weren't passing reply option into emailer at all. good spot

**Comment by easternbloc** [comment]
@JoeChapman fancy reviewing it then?

**Review by JoeChapman — APPROVED** [review]

**Pull request merged**
